import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stripe with next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col items-center gap-10 p-24">
          <Navbar />
          <div className="flex-1 flex w-full">
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
